server.port=8080

app.kafka.topic=events

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=event-streaming-platform

spring.kafka.listener.missing-topics-fatal=false

management.endpoints.web.exposure.include=health,info

