akka {
  loglevel = "INFO"
  actor {
    allow-java-serialization = on
    warn-about-java-serializer-usage = off
    serializers {
      java = "akka.serialization.JavaSerializer"
    }
    serialization-bindings {
      "java.io.Serializable" = java
    }
  }
}
