{{- if and (not .Values.microservices.enabled) .Values.db.enabled (not .Values.db.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-security-benchmark.dbSecretName" . }}
  labels:
    {{- include "ai-security-benchmark.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.db.username | default "admin" | b64enc }}
  password: {{ include "ai-security-benchmark.dbPassword" . }}
{{- end }}
